name: 'Firmware Build and Upload'
description: 'Builds firmware and uploads it to google drive'
inputs:
  file_path:  # id of input
    description: 'Who to greet'
    required: true
outputs:
  random-number:
    description: "Current Path"
    value: $GITHUB_SHA

defaults:
  run:
    shell: bash

runs:
  using: "composite"
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Current directory
      run: |
      pwd
    - name: File Existence
      uses: andstor/file-existence-action@v1.0.1
      with:
        # must provide full path to files
        files: "${{ inputs.file_path }}/workflows/file_check.yml"
        # This is poorly named, but it causes the step to fail if the files aren't found
        allow_failure: true
        