name: 'Firmware Build and Upload'
description: 'Builds firmware and uploads it to google drive'
inputs:
  firmware_path:  # id of input
    description: 'File path to main image and golden image'
    required: false

runs:
  using: "composite"
  steps:
    - name: Set branch name
      run: |
        if [ "${{ github.head_ref }}" == "" ]; then
          branch_name=`echo ${GITHUB_REF#refs/heads/}`
        else
          branch_name=${{ github.head_ref }}
        fi

        echo "BRANCH_NAME_RAW=$branch_name" >> $GITHUB_ENV

        # Now sanitize removing "/"
        branch_name=${branch_name////_}
        branch_name=${branch_name//refs_tags_/}
        echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
      shell: bash
    - name: Set SHA Short name
      run: |
        github_sha_short=`echo $GITHUB_SHA | cut -c1-8`
        echo "GITHUB_SHA_SHORT=$github_sha_short" >> $GITHUB_ENV
      shell: bash
    - run: git branch
    - run: |
        echo ${{ github.event.workflow_run.head_sha }}
        echo "BRANCH_SHA_1=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV
        echo "BRANCH_NAME_1=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
      shell: bash
        